name: hello
version: 0.1.2
synopsis: Hello
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2017-2020 Athae Eredh Siniath and Others
license: MIT
tested-with: GHC == 8.8.4

ghc-options: -Wall -Wwarn -fwarn-tabs

dependencies:
  - base
  - core-data
  - core-text
  - core-program >= 0.2.4

executables:
  hello:
    source-dirs:
      - src
    main: HelloMain.hs
    ghc-options: -threaded

tests:
  check:
    dependencies:
      - hspec
    ghc-options: -threaded
    source-dirs:
      - tests
    main: TestSuite.hs
    other-modules: []
